apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name:  cdf-watchdog
spec:
  environments:
    - name: prod
      build:
        from: main
  components:
    - name: uptime
      image: docker.io/elestio/uptime-kuma:{imageTagName}
      ports:
        - name: http
          port: 3001
      environmentConfig:
        - environment: prod
          imageTagName: latest
